name: Build
on:
    push:
        branches: [main, dev]
        paths-ignore:
            - "**/*.md"

jobs:
    build:
        name: Build and push
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Checkout builds
            uses: actions/checkout@v4
            with:
                repository: "pyoncord/bunny-builds"
                path: "builds"
                token: ${{ secrets.BUILDS_TOKEN }}
                ref: ${{ github.ref_name }}

          - uses: actions/setup-node@v4
            with:
                node-version: 20

          - name: Install pnpm and dependencies
            run: |
                npm i -g pnpm
                pnpm i\

          - name: Build
            run: pnpm build --release-branch=${{ github.ref_name }} --build-minify
          
          # TODO: Check for linting?

          - name: Push builds
            run: |
                rm $GITHUB_WORKSPACE/builds/* || true
                cp -r dist/* $GITHUB_WORKSPACE/builds || true
                cd $GITHUB_WORKSPACE/builds
                git config --local user.email "actions@github.com"
                git config --local user.name "GitHub Actions"
                git add .
                git commit -m "Build $GITHUB_SHA" || exit 0
                git push

          - name: Purge CDN cache
            run: |
                curl https://purge.jsdelivr.net/gh/pyoncord/bunny-build-infos@${{ github.ref_name }}/bunny.js
                
