name: Sync with I18n repository

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/core/i18n/default.json'
  workflow_dispatch:

jobs:
  sync:
    name: Synchronize strings
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
            repository: "amsyarasyiq/voyager"
            path: "main"
            token: ${{ secrets.PYLIX_TOKEN }}
      
      - name: Push
        run: |
          cp src/core/i18n/default.json $GITHUB_WORKSPACE/main/base/bunny.json
          cd $GITHUB_WORKSPACE/main
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Strings update from Bunny" || exit 0
          git push
